version: '3'

services:
  backend:
    # build:
    #   context: .
    #   dockerfile: compose/local/backend.Dockerfile
    build: ./src
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src:/backend
    ports:
      - 80:80
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:mypassword@db/db"

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "db"
    expose: 
      - 5432
  
  redis:
    image: redis:latest
  
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/celeryworker.Dockerfile
    command: celery -A app.celeryworker.worker worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./src:/celeryworker
    depends_on:
      - redis
      - backend

volumes:
  postgres_data:
